### ISSUE TITLE
suggestion copy assume file to nimscripter

### ISSUE THREAD

**Issue by bung87** [beef331/nimscripter#20]
I was trying to install my old project.
it throw `Error: Cannot satisfy the dependency on npeg 0.27.0 and npeg 1.0.1`

it cause by [assume](https://github.com/disruptek/assume)
in nimble file 
```
when not defined(release):
  requires "https://github.com/disruptek/balls >= 2.0.0 & < 4.0.0"
```
then ball relys on `ups`

in `ups` nimble file

```
requires "npeg >= 0.23.2 & < 1.0.0"
```

nimble recent added `taskRequires` feature, now I `nimble install nimble` on windows, still old nimble version.

that's a big long trace, but the fact is I dont need `balls`

**Comment by bung87** [comment]
How this been fixed, just curious

**Comment by beef331** [comment]
It's mostly under "wont fix", since there is no reason for me to do anything.
